#!/usr/bin/env bash

## Open links in system default browser
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)

# Get the default browser's .desktop file
desktop=$(xdg-settings get default-web-browser)

# Find the browser executable from .desktop entry
desktop_path=$(find ~/.local/share/applications ~/.nix-profile/share/applications /etc/profiles/per-user/$USER/share/applications /usr/share/applications -name "$desktop" 2>/dev/null | head -n1)
exec_cmd=$(grep -m1 '^Exec=' "$desktop_path" | cut -d= -f2 | awk '{print $1}')

# Optional: add --new-tab if it's Firefox
if [[ "$exec_cmd" == *"firefox"* || "$exec_cmd" == *"librewolf"* ]]; then
  cmd="$exec_cmd --new-tab"
else
  cmd="$exec_cmd"
fi

close_dash() {
  "$EWW" --config "$CFG" close \
    background profile system clock uptime music github \
    reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
  rm -rf "$FILE"
}

# Open URLs
if [[ "$1" == "--mail" ]]; then
  close_dash && $cmd "https://mail.google.com"
elif [[ "$1" == "--gh" ]]; then
  close_dash && $cmd "https://github.com"
elif [[ "$1" == "--rd" ]]; then
  close_dash && $cmd "https://reddit.com"
elif [[ "$1" == "--tw" ]]; then
  close_dash && $cmd "https://twitter.com"
elif [[ "$1" == "--yt" ]]; then
  close_dash && $cmd "https://youtube.com"
fi
